### ISSUE TITLE
Error when running with v1.4.0 of octodns

### ISSUE THREAD

**Issue by xt0rted** [octodns/octodns-rackspace#33]
Dependabot opened a PR updating octodns from v1.0.0 to v1.4.0 and now when octodns runs I get an error which is included below.

I have another project that's using v1.4.0 with the latest Azure (0.0.7) & Cloudflare (0.0.3) providers which is running just fine, it seems to be just this provider causing an issue.

I'm running via https://github.com/solvaholic/octodns-sync but I don't think that has anything to do with the error.

requirements.txt

```text
octodns==1.4.0
octodns_rackspace==0.0.1
```

production.yaml

```yaml
---
providers:
  config:
    class: octodns.provider.yaml.YamlProvider
    directory: zones
    default_ttl: 300
  rackspace:
    class: octodns.provider.rackspace.RackspaceProvider
    username: env/RACKSPACE_API_USERNAME
    api_key: env/RACKSPACE_API_KEY
manager:
  max_workers: 2
  plan_outputs:
    html:
      class: octodns.provider.plan.PlanHtml
zones:
  # ...
```

<details><summary>Run log</summary>
<pre>
2024-02-09T00:47:55  [139722632227904] INFO  Manager __init__: config_file=production.yaml, (octoDNS 1.4.0)
2024-02-09T00:47:55  [139722632227904] INFO  Manager _config_executor: max_workers=2
2024-02-09T00:47:55  [139722632227904] INFO  Manager _config_include_meta: include_meta=False
2024-02-09T00:47:55  [139722632227904] INFO  Manager _config_auto_arpa: auto_arpa=False
2024-02-09T00:47:55  [139722632227904] INFO  Manager __init__: global_processors=[]
2024-02-09T00:47:55  [139722632227904] INFO  Manager __init__: global_post_processors=[]
2024-02-09T00:47:55  [139722632227904] INFO  Manager __init__: provider=config (octodns.provider.yaml 1.4.0)
2024-02-09T00:47:55  [139722632227904] ERROR Manager _get_{}_class: Unable to import module octodns.provider.rackspace.RackspaceProvider
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/octodns/manager.py", line 333, in _get_named_class
    module, version = self._import_module(module_name)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/octodns/manager.py", line 319, in _import_module
    module = import_module(current)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'octodns.provider.rackspace'
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/octodns/manager.py", line 333, in _get_named_class
    module, version = self._import_module(module_name)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/octodns/manager.py", line 319, in _import_module
    module = import_module(current)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'octodns.provider.rackspace'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.13/x64/bin/octodns-sync", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/octodns/cmds/sync.py", line 56, in main
    manager = Manager(args.config_file)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/octodns/manager.py", line 123, in __init__
    self.providers = self._config_providers(providers_config)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/octodns/manager.py", line 215, in _config_providers
    _class, module, version = self._get_named_class(
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/octodns/manager.py", line 3[38](https://github.com/paramax/dns/actions/runs/7838025325/job/21388786004?pr=92#step:5:40), in _get_named_class
    raise ManagerException(
octodns.manager.ManagerException: Unknown provider class: octodns.provider.rackspace.RackspaceProvider, production.yaml, line 8, column 5
<pre>
</details>

**Comment by yzguy** [comment]
The providers were broken out of `octodns` to separate repos, eg `octodns-rackspace` (https://github.com/octodns/octodns/pull/855), so the provider configuration you have now is no longer valid. Although that happened in `octodns==0.9.15` so I'm surprised you didn't hit that before.

You can view the new one here: https://github.com/octodns/octodns-rackspace?tab=readme-ov-file#configuration

Just need to change `class: octodns.provider.rackspace.RackspaceProvider` to `class: octodns_rackspace.RackspaceProvider`

**Comment by xt0rted** [comment]
Well that's embarrassing. After checking my other project that one had the class names updated 2 years ago but I missed it in this one. Renamed the class and it's working again. Thanks for the help.
